#!/bin/sh -l
# every bare repo in ~/git shall have a symlink in hooks/
# pointing to this file
# setup with:
#  for i in git/*.git; do ln -sfn $XDG_CONFIG_HOME/git/post-receive $i/hooks/post-receive ; done

spawn() {
	echo "trigger ${1} ${2} >&2
	s="$PWD/hooks/$1"
	[ -e "$s" ] || return
	export NQDIR="$HOME"
	nq "$s" "$2"
}

while read old newrev refname; do
	zero="0000000000000000000000000000000000000000"
	if [ "$newrev" = "$zero" ]; then
		newrev_type=delete
	else
		newrev_type=$(git cat-file -t $newrev)
	fi

	case "$refname","$newrev_type" in
	refs/tags/*,commit|refs/tags/*,tag)
		spawn ci-release "${refname#refs/tags/}"
		;;
	refs/heads/*,commit)
		spawn ci-commit "$newrev"
		;;
	esac
done

exec git update-server-info
