#!/bin/sh
name=${PWD##*/}
name=${name%.git}

if test -e git-daemon-export-ok; then
  for upstream in $(git config --get-all receive.mirror); do
    url=$(printf "$upstream" "$name")
    git push --mirror -f "${url}" &
  done
fi

git update-server-info &

wait
