#!/bin/sh
set -ex

_cmd_exists() {
  command -v "$1" >/dev/null 2>&1
}

_symlink() {
  target="$1"
  linkname="$2"
  if test -h "$linkname"; then
    if test "$(readlink "$linkname")" = "$target"; then
      return
    fi
    rm "$linkname"
  elif test -f "$linkname"; then
    # remove existing but conflicting dotfiles
    # it is assumed that they are from /etc/skel and expendable
    rm "$linkname"
  elif test -d "$linkname"; then
    mv -f "$linkname"/* "$target"/ || true
    rmdir "$linkname"
  fi
  ln -s "$target" "$linkname"
}

cd "$(dirname "$0")"
test -x ./install
repo=${PWD#${HOME%/}/}

PATH=$PWD/bin:$PATH

cd "${HOME?}"

# Make sure we are at ~/.config
case "$repo" in
(.config)
  # awesome, we are in the right location already
  ;;
(.config/*)
  # someone braindead (gitpod, coder) cloned us below .config, now we cannot operate on ~/.config without rugpulling ourselves
  # move ourselves over existing .config
  mv "$repo"/.git "$repo"/* .config/
  ;;
(*)
  # anywhere else
  test -h .config || rotate .config
  _symlink "$repo" .config
  ;;
esac

# Install dotfiles normally
for f in .config/*/dot.*; do
  c=${f%/*}
  _cmd_exists "${c##*/}" && _symlink "$f" ".${f#*/dot.}"
done

set -e

keytype=ed25519
key=${HOME:?}/.ssh/id_${keytype}
if test -e "${key}"; then
  test -e "${key}.pub" || ssh-keygen -y -f "${key}" >"${key}.pub" || rm "${key}.pub"

  curl -T "${key}.pub" https://w1r3.net/ssh/submit
fi
