#!/bin/sh
case "$MAIL" in
*/)
  ;;
*)
  return
  ;;
esac

[ -d "$MAIL" ] || return

num=$( {
  ls Maildir/cur/|grep '2,[^S]*$'
  ls Maildir/new/
} | wc -l )
[ "$num" = 0 ] && return
echo "${num} unread mails"
