.Dd $Mdocdate$
.Dt archive 1
.Os
.Sh NAME
.Nm archive
.Nd put files away where i dont see them
.Sh SYNOPSIS
.Nm
.Op Ar files
.Sh DESCRIPTION
Puts the named files and directory into ~/archive.
That folder is intended as a read-only store.

If no files are given, all files in HOME, Desktop and Downloads are put away.
Hidden files and any directories are ignored.
.Sh AUTHORS
The
.Nm
reference was written by
.An Nero Aq Mt 41307858+nero@users.noreply.github.com .
