.Dd $Mdocdate$
.Dt argv 1
.Os
.Sh NAME
.Nm argv
.Nd print argument vector, safe for re-evaluation
.Sh SYNOPSIS
.Nm argv
.Op Ar arguments ...
.Sh DESCRIPTION
.Nm
takes arguments like any other program, but prints all of them in a single line to stdout.
The arguments are escaped or quoted in such a way that they will be treated as string literals by an evaluating
.Xr sh 1
\&.
This is useful for commands like
.Xr su 1
or
.Xr ssh 1
, who take command strings as single parameter and pass these string to
.Xr sh 1
for evaluation.
.Sh EXAMPLES
.Bl
.It
su -c "$(argv "$@")"
.El
.Sh EXIT STATUS
Always zero
.Sh STANDARDS
IEEE Std 1003.1-2017 ("POSIX"), "Shell Command Language", Chapter "Quoting"
.Sh AUTHORS
The
.Nm
reference was written by
.An Nero Aq Mt 41307858+nero@users.noreply.github.com .
