.Dd $Mdocdate$
.Dt osc 1
.Os
.Sh NAME
.Nm osc
.Nd Run an Operating System Command against your terminal
.Sh SYNOPSIS
.Nm
.Ar data
.Op Ar more data
.Sh DESCRIPTION
OSC sequences encapsulate string data for use by the terminal.
All arguments are joined with a semicolon, encapsulated and sent to stdout.
As OSC sequences are highly dependent on the used terminal, the actual format of the data varies.
.Sh EXAMPLES
.Ql osc 2 "Window Title"
Tell xterm to set its window title.
.Sh AUTHORS
The
.Nm
reference was written by
.An Nero Aq Mt 41307858+nero@users.noreply.github.com .
