.Dd $Mdocdate$
.Dt quote 1
.Os
.Sh NAME
.Nm quote
.Nd print argument vector, safe for re-evaluation by
.Xr sh 1
\&.
.Sh SYNOPSIS
.Nm
.Op Ar arguments ...
.Sh DESCRIPTION
.Nm
takes an arbitrary amount of arguments, escapes and quotes them, and prints them to stdout so they can be used as string literals in a command string.
This is useful for commands like
.Xr su 1
or
.Xr ssh 1
, who take command strings as single parameter and pass these string to
.Xr sh 1
for evaluation.
.Sh EXAMPLES
.Bl
.It
su -c "$(quote "$@")"
.El
.Sh STANDARDS
IEEE Std 1003.1-2017 ("POSIX"), "Shell Command Language", Chapter "Quoting"
.Sh AUTHORS
The
.Nm
reference was written by
.An Nero Aq Mt 41307858+nero@users.noreply.github.com .
