.Dd $Mdocdate$
.Dt quote_ere 1
.Os
.Sh NAME
.Nm quote_ere
.Nd Filter to quote POSIX Extended Regular Expressions
.Sh SYNOPSIS
.Nm
No arguments accepted.
.Sh DESCRIPTION
The
.Nm
util takes a string on stdin and emits a string on stdout that can be used
as string literal in a extended regular expression.
.Sh SEE ALSO
.Xr regex 7
.Sh AUTHORS
The
.Nm
reference was written by
.An Nero Aq Mt 41307858+nero@users.noreply.github.com .
.Sh BUGS
I didn't even confirm that this program is correct.
If its not, i'll patch it later.
