.Dd $Mdocdate$
.Dt trust-certs 1
.Os
.Sh NAME
.Nm trust-certs
.Nd Mark one or multiple TLS certificates as trusted
.Sh SYNOPSIS
.Nm
.Ar crt_file1
.Op Ar crt_file2 ...
.Sh DESCRIPTION
The
.Nm
utility is meant to speed up setting up your Linux system for your work environment.
Download the crt files and give them as argument to this script.
sudo functionality might be used to do system-wide configuration.
.Sh EXIT STATUS
Non-zero upon any error
.Sh EXAMPLES
.Sh AUTHORS
The
.Nm
reference was written by
.An Nero Aq Mt 41307858+nero@users.noreply.github.com .
.Sh SECURITY CONSIDERATIONS
